### ISSUE TITLE
Not Seeing any feedback (not running tests?) on fresh lib m1 mac

### ISSUE THREAD

**Issue by dnsco** [MFranceschi6/vscode-swift-test-adapter#3] opened 2021-06-25 07:54 UTC
I wrote an intentionally failing test, when I click the run icon in the gutter it briefly flashes, but then I don't see any feedback.

Here's the test file:

```Swift
    import Foundation
    import XCTest

    @testable import swiftlib

    final class swiftlibTests: XCTestCase {
        func testExample() {                        
            XCTAssert(false)
        }
    }
```

I enabled debug output so here's what I see:

```
[2021-06-25 07:46:17.248] [DEBUG] [
  'test',
  '--enable-test-discovery',
  '--filter',
  'swiftlibTests.swiftlibTests',
  '-Xswiftc',
  '-Xfrontend',
  '-Xswiftc',
  '-serialize-debugging-options'
]
[2021-06-25 07:46:17.311] [INFO] [0/0] Build complete!
```

I noticed the ```[0/0] Build complete!``` I got suspicious so I ran the command manually in the terminal and I see:

``` 
% swift test --enable-test-discovery --filter swiftlibTests -Xswiftc -Xfrontend -Xswiftc -serialize-debugging-options
warning: '--enable-test-discovery' option is deprecated; tests are automatically discovered on all platforms
[0/0] Build complete!
Test Suite 'Selected tests' started at 2021-06-25 01:44:28.692
Test Suite 'swiftlibPackageTests.xctest' started at 2021-06-25 01:44:28.692
Test Suite 'swiftlibTests' started at 2021-06-25 01:44:28.692
Test Case '-[swiftlibTests.swiftlibTests testExample]' started.
/Users/denniscollinson/workspace/swiftlib/Tests/swiftlibTests/swiftlibTests.swift:8: error: -[swiftlibTests.swiftlibTests testExample] : XCTAssertTrue failed
Test Case '-[swiftlibTests.swiftlibTests testExample]' failed (0.047 seconds).
Test Suite 'swiftlibTests' failed at 2021-06-25 01:44:28.739.
	 Executed 1 test, with 1 failure (0 unexpected) in 0.047 (0.047) seconds
Test Suite 'swiftlibPackageTests.xctest' failed at 2021-06-25 01:44:28.740.
	 Executed 1 test, with 1 failure (0 unexpected) in 0.047 (0.048) seconds
Test Suite 'Selected tests' failed at 2021-06-25 01:44:28.740.
	 Executed 1 test, with 1 failure (0 unexpected) in 0.047 (0.048) seconds
```

The test is failing correctly when I run it from the command line.

Not sure how else I can debug this.

Thanks for taking the time to make this library!

**Comment by MFranceschi6** [comment] 2021-06-25 09:01
Hi, thank you for your feedback.

I don't have a mac where I can test the problem and try to fix it.

The library uses the output of `swift test` command to give feedback about the tests And it prints only the errors in its log:
```
[2021-06-25 08:49:30.480] [INFO] Starting test suite: swiftlibTests.swiftlibTests
[2021-06-25 08:49:30.480] [DEBUG] [
  'test',
  '--enable-test-discovery',
  '--filter',
  'swiftlibTests.swiftlibTests',
  '-Xswiftc',
  '-Xfrontend',
  '-Xswiftc',
  '-serialize-debugging-options'
]
[2021-06-25 08:49:30.523] [INFO] [1/1] Planning build
[2021-06-25 08:49:30.523] [INFO] [1/1] Planning build
[2021-06-25 08:49:30.523] [INFO] 
[2021-06-25 08:49:30.523] [INFO] * Build Completed!
[2021-06-25 08:49:30.559] [INFO] /home/matte/swiftlib/Tests/swiftlibTests/swiftlibTests.swift:9: error: swiftlibTests.testExample : XCTAssertTrue failed - 
```

The problem is in the output of the swift test command this is the output under linux:
```
swift test --enable-test-discovery --filter swiftlibTests -Xswiftc -Xfrontend -Xswiftc -serialize-debugging-options
warning: '--enable-test-discovery' option is deprecated; tests are automatically discovered on all platforms
Test Suite 'Selected tests' started at 2021-06-25 10:39:52.878
Test Suite 'swiftlibTests' started at 2021-06-25 10:39:52.879
Test Case 'swiftlibTests.testExample' started at 2021-06-25 10:39:52.879
/home/matte/swiftlib/Tests/swiftlibTests/swiftlibTests.swift:9: error: swiftlibTests.testExample : XCTAssertTrue failed -
Test Case 'swiftlibTests.testExample' failed (0.0 seconds)
Test Suite 'swiftlibTests' failed at 2021-06-25 10:39:52.879
Executed 1 test, with 1 failure (0 unexpected) in 0.0 (0.0) seconds
Test Suite 'Selected tests' failed at 2021-06-25 10:39:52.879
Executed 1 test, with 1 failure (0 unexpected) in 0.0 (0.0) seconds
```

So I know  how to move but I need the output of the following command:

```
swift test --enable-test-discovery -l -Xswiftc -Xfrontend -Xswiftc -serialize-debugging-options
```

```
swift test --enable-test-discovery --filter "swiftlibTests.swiftlibTests" -Xswiftc -Xfrontend -Xswiftc -serialize-debugging-options
```

```
swift test --enable-test-discovery --filter "swiftlibTests.swiftlibTests/testExample" -Xswiftc -Xfrontend -Xswiftc -serialize-debugging-options
```

And also to confirm that the output of `swift test` is on the stdout so:
```
swift test --enable-test-discovery --filter "swiftlibTests.swiftlibTests/testExample" -Xswiftc -Xfrontend -Xswiftc -serialize-debugging-options 1> /dev/null
```
```
swift test --enable-test-discovery --filter "swiftlibTests.swiftlibTests/testExample" -Xswiftc -Xfrontend -Xswiftc -serialize-debugging-options 2> /dev/null
```

Thank you very much for the support

**Comment by dnsco** [comment] 2021-06-25 17:54
Here we go!

```
$ swift test --enable-test-discovery -l -Xswiftc -Xfrontend -Xswiftc -serialize-debugging-options
warning: '--enable-test-discovery' option is deprecated; tests are automatically discovered on all platforms
[0/0] Build complete!
swiftlibTests.swiftlibTests/testExample
```

```
$ swift test --enable-test-discovery --filter "swiftlibTests.swiftlibTests" -Xswiftc -Xfrontend -Xswiftc -serialize-debugging-options
warning: '--enable-test-discovery' option is deprecated; tests are automatically discovered on all platforms
[0/0] Build complete!
Test Suite 'Selected tests' started at 2021-06-25 11:48:38.282
Test Suite 'swiftlibPackageTests.xctest' started at 2021-06-25 11:48:38.282
Test Suite 'swiftlibTests' started at 2021-06-25 11:48:38.282
Test Case '-[swiftlibTests.swiftlibTests testExample]' started.
/Users/denniscollinson/workspace/swiftlib/Tests/swiftlibTests/swiftlibTests.swift:8: error: -[swiftlibTests.swiftlibTests testExample] : XCTAssertTrue failed
Test Case '-[swiftlibTests.swiftlibTests testExample]' failed (0.039 seconds).
Test Suite 'swiftlibTests' failed at 2021-06-25 11:48:38.321.
	 Executed 1 test, with 1 failure (0 unexpected) in 0.039 (0.039) seconds
Test Suite 'swiftlibPackageTests.xctest' failed at 2021-06-25 11:48:38.321.
	 Executed 1 test, with 1 failure (0 unexpected) in 0.039 (0.039) seconds
Test Suite 'Selected tests' failed at 2021-06-25 11:48:38.321.
	 Executed 1 test, with 1 failure (0 unexpected) in 0.039 (0.039) seconds
```

```
bash-3.2$ swift test --enable-test-discovery --filter "swiftlibTests.swiftlibTests/testExample" -Xswiftc -Xfrontend -Xswiftc -serialize-debugging-options
warning: '--enable-test-discovery' option is deprecated; tests are automatically discovered on all platforms
[0/0] Build complete!
Test Suite 'Selected tests' started at 2021-06-25 11:49:29.633
Test Suite 'swiftlibPackageTests.xctest' started at 2021-06-25 11:49:29.633
Test Suite 'swiftlibTests' started at 2021-06-25 11:49:29.633
Test Case '-[swiftlibTests.swiftlibTests testExample]' started.
/Users/denniscollinson/workspace/swiftlib/Tests/swiftlibTests/swiftlibTests.swift:8: error: -[swiftlibTests.swiftlibTests testExample] : XCTAssertTrue failed
Test Case '-[swiftlibTests.swiftlibTests testExample]' failed (0.029 seconds).
Test Suite 'swiftlibTests' failed at 2021-06-25 11:49:29.662.
	 Executed 1 test, with 1 failure (0 unexpected) in 0.029 (0.029) seconds
Test Suite 'swiftlibPackageTests.xctest' failed at 2021-06-25 11:49:29.662.
	 Executed 1 test, with 1 failure (0 unexpected) in 0.029 (0.029) seconds
Test Suite 'Selected tests' failed at 2021-06-25 11:49:29.662.
	 Executed 1 test, with 1 failure (0 unexpected) in 0.029 (0.030) seconds
```

```
bash-3.2$ swift test --enable-test-discovery --filter "swiftlibTests.swiftlibTests/testExample" -Xswiftc -Xfrontend -Xswiftc -serialize-debugging-options 1> /dev/null
warning: '--enable-test-discovery' option is deprecated; tests are automatically discovered on all platforms
Test Suite 'Selected tests' started at 2021-06-25 11:50:06.386
Test Suite 'swiftlibPackageTests.xctest' started at 2021-06-25 11:50:06.386
Test Suite 'swiftlibTests' started at 2021-06-25 11:50:06.386
Test Case '-[swiftlibTests.swiftlibTests testExample]' started.
/Users/denniscollinson/workspace/swiftlib/Tests/swiftlibTests/swiftlibTests.swift:8: error: -[swiftlibTests.swiftlibTests testExample] : XCTAssertTrue failed
Test Case '-[swiftlibTests.swiftlibTests testExample]' failed (0.028 seconds).
Test Suite 'swiftlibTests' failed at 2021-06-25 11:50:06.414.
	 Executed 1 test, with 1 failure (0 unexpected) in 0.028 (0.028) seconds
Test Suite 'swiftlibPackageTests.xctest' failed at 2021-06-25 11:50:06.414.
	 Executed 1 test, with 1 failure (0 unexpected) in 0.028 (0.028) seconds
Test Suite 'Selected tests' failed at 2021-06-25 11:50:06.414.
	 Executed 1 test, with 1 failure (0 unexpected) in 0.028 (0.028) seconds
```

```
bash-3.2$ swift test --enable-test-discovery --filter "swiftlibTests.swiftlibTests/testExample" -Xswiftc -Xfrontend -Xswiftc -serialize-debugging-options 2> /dev/null
[0/0] Build complete
```

Looks like it's outputting test all suite info on stderr, weird!

Thanks again for taking the time to do this! Let me know if there's anything else you need 🤠

**Comment by MFranceschi6** [comment] 2021-06-26 10:59
Hi, thank you very much.

Yes, they have implemented it very differently on linux the output is on the stdout...

 I've just pushed the branch `issue-3` with the fix for this issue.

I hope it works. But before publishing it I'd ask you to test it if you can.

You just need to clone this repo and switch to the branch then
`npm i`
`npm run watch`

open the debug panel with any of the typescript file opened.
Click on `Run and Debug`
and the options should show `VS Code Extension development`

That should open a new vscode window. Just open the swift project and see if it now works.

I'm sorry to have you being my tester but I really don't have access to any mac right now.

**Comment by dnsco** [comment] 2021-06-26 19:16
Thanks! It works!

Thanks again for taking the time to do this  💖

**Comment by MFranceschi6** [comment] 2021-06-28 17:29
Glad to hear, I will release the update in few minutes.

:smile:

**Closed as completed** 2021-06-28 17:30 UTC
Labels: mac
